### ISSUE TITLE
can we remove tini?

### ISSUE THREAD

**Issue by ltalirz** [materialscloud-org/mc-docker-stack#3]
https://github.com/materialscloud-org/mc-docker-stack/blob/37437fd16de6a433e55cfd51239b6d8fd4d9d242/Dockerfile#L122-L127

See https://github.com/krallin/tini#using-tini

**Comment by ltalirz** [comment]
It seems all one apparently needs to do is to pass the `--init` flag to `docker run`.

In our case, the container is started by the dockerspawner, and I guess the configuration option will be something like
```
c.DockerSpawner.extra_run_kwargs = {
    'init': '',
}
```
and needs to be added here:
https://github.com/materialscloud-org/openstack-ansible/blob/738b83e2f8295e944f24f2e62079c41fc88aa04d/roles/mc_jupyter/templates/jupyterhub_config.py#L19-L25



See https://github.com/jupyterhub/dockerspawner/blob/19e26f3d1f5fd196b2a750f9e9c525bcfa0c95fb/dockerspawner/dockerspawner.py#L480-L487
and
https://github.com/jupyterhub/jupyterhub/issues/1599

**Comment by ltalirz** [comment]
Done in 69ccdb54338c0e428c56d292e062370b6dd2bd9b
Still need to check whether this actually works... (@oschuett how do we know?)

**Comment by oschuett** [comment]
I believe the main purpose of tini was to clean up child processes. So, I would just check if any processes remain after a container was forcefully shutdown.

**Comment by ltalirz** [comment]
Thanks, Ole!

Note to self: The `extra_run_kwargs` didn't do the trick yet...
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
    1 scienti+  20   0   19948   3588   3260 S   0.0  0.0   0:00.03 start-sing+
```
process with PID 1 should be`init` (as verified with running the docker image locally)

**Comment by ltalirz** [comment]
it's `extra_start_kwargs`, but even this doesn't work because `docker-py` does no longer support it...

No solution so far: https://github.com/jupyterhub/dockerspawner/issues/192

**Comment by ltalirz** [comment]
Turns out the solution is
```
c.DockerSpawner.extra_host_config.update({ 'init': True })
```
